guilds:
- name: "Brinkers"
  roles:
    relevantParsing: false
    relevantFlexing: false
    relevantRepetition: false
    legend: true
    ultimateFlexing: false
    ultimateRepetition: true
    datacenter: false
    menu: true

  guildId: 1209347741038280725
  channelId: 1209347742174806048

  physicalDatacenters:
  - name: "NA"

  encounters:
  - ids: [1060, 1047, 1039, 1073]
    name: "The Unending Coil of Bahamut (Ultimate)"
    defaultRoles: true
    totalWeaponsAvailable: 15
    the: "Legendary"
    difficulty: "Ultimate"

  - ids: [1061, 1048, 1042, 1074]
    name: "The Weapon's Refrain (Ultimate)"
    defaultRoles: true
    totalWeaponsAvailable: 15
    the: "Ultimate"
    difficulty: "Ultimate"

  - ids: [1062, 1050, 1075]
    name: "The Epic of Alexander (Ultimate)"
    defaultRoles: true
    totalWeaponsAvailable: 17
    the: "Perfect"
    difficulty: "Ultimate"

  - ids: [1065, 1076]
    name: "Dragonsong's Reprise (Ultimate)"
    defaultRoles: true
    totalWeaponsAvailable: 19
    the: "Heavenly"
    difficulty: "Ultimate"

  - ids: [1068, 1077]
    name: "The Omega Protocol (Ultimate)"
    defaultRoles: true
    totalWeaponsAvailable: 21
    the: "Alpha"
    difficulty: "Ultimate"

  - ids: [1079]
    name: "Futures Rewritten (Ultimate)"
    defaultRoles: true
    totalWeaponsAvailable: 21
    the: "Roommate"
    difficulty: "Ultimate"

  - ids: [1085]
    name: "Dancing Mad (Ultimate)"
    defaultRoles: true
    totalWeaponsAvailable: 21
    the: "Mad"
    difficulty: "Ultimate"

  menu:
  - name: menuMain
    type: menuMain
    title: __Verify Clears__
    description: |
      Use the button below to verify your FFXIV character and assign roles based on your FFLogs clears.
    fields:
    - name: Verify Clears
      value: >
        Verifying your character will confirm ownership of your FFXIV character
        and analyze the FFLogs attached to it. Once verified, Clearingway will
        assign roles based on your confirmed Ultimate clears.
    buttons:
    - label: Verify Clears
      style: 3
      menuName: menuVerify
      menuType: menuVerify
